spring:
  application:
    name: reservation-microservice # Nom de l'application pour identification dans Eureka
  cloud:
    uri: http://localhost:8888 # Adresse de votre Config Server
    config:
      import: "optional:configserver:" # Utilisation correcte de configserver avec optional pour éviter l'erreur
      import-check:
        enabled: false # Désactiver la vérification de l'importation de configuration
  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka/ # Adresse de votre Eureka Server

management:
  endpoints:
    web:
      exposure:
        include: "*" # Expose tous les endpoints
  metrics:
    export:
      prometheus:
        enabled: true
  tracing:
    sampling:
      probability: 1.0 # Taux d'échantillonnage pour la traçabilité
  zipkin:
    endpoint: http://localhost:9411/api/v2/spans # URL du serveur Zipkin

resilience4j:
  retry:
    instances:
      myRetry:
        max-attempts: 3
        wait-duration: 500ms
  rate-limiter:
    instances:
      myRateLimiter:
        limit-for-period: 5
        limit-refresh-period: 1s
        timeout-duration: 500ms
  circuitbreaker:
    instances:
      reservationCircuitBreaker:
        registerHealthIndicator: true
        slidingWindowSize: 5
        minimumNumberOfCalls: 3
        failureRateThreshold: 50
        waitDurationInOpenState: 5s
